# Generated by Django 4.0.3 on 2022-03-22 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='Group',
            field=models.CharField(choices=[('1', 'Veg'), ('2', 'Fruit'), ('3', 'Grain'), ('4', 'Protein'), ('5', 'Dairy'), ('6', 'Confectionary'), ('7', 'Unknown')], default='7', max_length=20),
        ),
        migrations.AlterField(
            model_name='image',
            name='Approved_by',
            field=models.CharField(max_length=50, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='image',
            name='Created_On',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
