# Generated by Django 4.0.3 on 2022-03-22 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0002_image_group_alter_image_approved_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='Approved_by',
        ),
    ]
